### ISSUE TITLE
Logtail breaks with Rails 7.1+ and latest Sidekiq

### ISSUE THREAD

**Issue by kmewhort** [logtail/logtail-ruby-rails#30]
Sidekiq made a change for Rails 7.1 that now calls `Rails.logger.broadcast_to`: https://github.com/sidekiq/sidekiq/commit/916a5645b4576c4d6d82e77230a2d33e751c223b. 

However, if the `Rails.logger` is set to a `Logtail::Logger`, the sidekiq process will crash with an `undefined method` error (as `broadcast_to` is not a method on `Logtail::Logger`).

**Comment by curusarn** [comment]
Hi @kmewhort,

Thank you for reporting this.

I'm passing the issue to the team. We'll make sure to keep you posted about any updates.

Thanks again for reaching out.

**Comment by caleb** [comment]
@kmewhort Was this error causing your jobs to fail and retry?

I had upgraded my Sidekiq and jobs were getting run twice (or more).

I don't understand how that would happen since the error seems to indicate that sidekiq would fail to initialize, but removing the logtail gem stopped it from happening.

**Comment by kmewhort** [comment]
Sounds unrelated.  This one was hit for me on worker startup.

**Comment by caleb** [comment]
Gotcha.

I have a Sidekiq job that uploads files to a server, and with the logtail-rails gem installed it would upload twice (tacking on a timestamp to avoid collisions). Simply removing the gem fixed the issue. It only happened after upgrading to rails 7.1 and bumping the Sidekiq version. I wonder if there is something else going on.

**Comment by PetrHeinz** [comment]
Hello @kmewhort and @caleb,

the issue should be fixed in [logtail-rails 0.2.5](https://rubygems.org/gems/logtail-rails/versions/0.2.5) gem.

I've used the provided example project, installed and configured Sidekiq to validate, and both workers and logs were behaving as expected.

Thank you for reporting this. If you have questions or followups please don't hesitate to reopen it or create a new issue 🙏
